# Base configs
baseurl: "https://photography.rampatra.com"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Isaac"
subtitle: "See the world through my eyes!"
author: "Isaac"
header:
 title: "Photography"
 subtitle: "by Isaac"
footer:
 name: "Hey there, I'm Isaac"
 bio: "I am a scientist, photographer, and a person loves playing musical instrument. But more than that, I love people who are the masterpiece of God!"
web_design: "AJ"

social_urls:
  instagram: "https://www.instagram.com/2saac_ch"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
